
GET http://localhost:3000/api/proyectos

###
POST http://localhost:3000/api/proyectos
Content-Type: application/json

{
  "titulo": "Proyecto de prueba",
  "descripcion": "Esta es la descripcion",
  "url": "http://www.google.es",
  "cliente": "Google",
  "urlCliente": "http://www.google.com/quien-somos"
}

###
PUT http://localhost:3000/api/proyectos/5ec173ea4a335805d4b49966
Content-Type: application/json

{
  "titulo": "Proyecto EDITADO V5",
  "descripcion": "Esta es la descripcion",
  "url": "http://www.google.es",
  "cliente": "Google",
  "urlCliente": "http://www.google.com/quien-somos"
}

###
DELETE http://localhost:3000/api/proyectos/5ec170704d6f5a7f5be8b5e0